# Generated by Django 3.0.7 on 2020-10-27 18:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('content', '0001_initial'), ('content', '0002_auto_20200624_1451'), ('content', '0003_auto_20200624_2221'), ('content', '0004_auto_20200624_2245'), ('content', '0005_auto_20200627_0853'), ('content', '0006_auto_20200630_0849'), ('content', '0007_auto_20200630_1524'), ('content', '0008_auto_20200630_1536'), ('content', '0009_auto_20200630_1537'), ('content', '0010_screen_last_change'), ('content', '0011_auto_20200702_0949'), ('content', '0012_auto_20200709_1657'), ('content', '0013_auto_20200709_1659'), ('content', '0014_auto_20200716_1226'), ('content', '0015_auto_20200717_1541'), ('content', '0016_auto_20200717_1546'), ('content', '0017_auto_20200717_1546'), ('content', '0018_auto_20200717_1548')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=64, verbose_name='название')),
                ('image', models.FileField(upload_to='images_prototypes/', verbose_name='изображение')),
                ('image_hover', models.FileField(default='', upload_to='images_prototypes/hover/', verbose_name='hover')),
                ('base_layout', tinymce.models.HTMLField(default='', verbose_name='начальный макет')),
            ],
            options={
                'verbose_name': 'прототип',
                'verbose_name_plural': 'прототипы',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='название')),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Prototype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='название')),
                ('slug', models.CharField(max_length=64, verbose_name='slug')),
                ('two_in_row', models.BooleanField(default=False, verbose_name='По 2 элемента')),
            ],
            options={
                'verbose_name': 'картегория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='CategoryPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Category', verbose_name='категория')),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Prototype')),
            ],
            options={
                'verbose_name': 'картегория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='название')),
                ('image', models.FileField(upload_to='images_elements/', verbose_name='изображение')),
                ('layout', models.TextField(verbose_name='макет')),
                ('category_prototype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.CategoryPrototype')),
                ('active', models.BooleanField(default=True, verbose_name='on')),
            ],
            options={
                'verbose_name': 'графический элемент',
                'verbose_name_plural': 'графические элементы',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Значение')),
                ('slug', models.CharField(max_length=64, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Project')),
                ('layout', models.TextField(default='', verbose_name='макет')),
                ('title', models.CharField(default='', max_length=32, verbose_name='название')),
                ('last_change', models.DateTimeField(default=datetime.datetime(2020, 7, 17, 15, 48, 4, 179432, tzinfo=utc), verbose_name='последние изменение')),
            ],
            options={
                'verbose_name': 'экран',
                'verbose_name_plural': 'экраны',
            },
        ),
    ]
