# Generated by Django 3.0.7 on 2020-06-24 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, verbose_name='название')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='название')),
                ('image', models.ImageField(upload_to='images_prototypes/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'прототип',
                'verbose_name_plural': 'прототипы',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_screen', models.TextField(verbose_name='макет')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Project')),
            ],
            options={
                'verbose_name': 'экран',
                'verbose_name_plural': 'экраны',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='prototype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Prototype'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='название')),
                (
                'prototype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Prototype')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='название')),
                ('image', models.ImageField(upload_to='images_elements/', verbose_name='изображение')),
                ('layout_element', models.TextField(verbose_name='макет')),
                (
                'group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.GroupElements')),
            ],
            options={
                'verbose_name': 'графический элемент',
                'verbose_name_plural': 'графические элементы',
            },
        ),
    ]
