# Generated by Django 3.0.7 on 2020-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototype',
            name='image',
            field=models.FileField(upload_to='images_prototypes/', verbose_name='изображение'),
        ),
    ]
