# Generated by Django 3.0.7 on 2020-10-27 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial_squashed_0018_auto_20200717_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='последние изменение'),
        ),
    ]
