# Generated by Django 3.0.7 on 2020-06-24 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0002_auto_20200624_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prototype',
            old_name='title',
            new_name='device_name',
        ),
    ]
