# Generated by Django 3.0.7 on 2020-11-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201027_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='image',
            new_name='light_image',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='layout',
            new_name='light_layout',
        ),
    ]
