# Generated by Django 3.0.7 on 2020-11-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201102_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototype',
            name='base_layout',
        ),
        migrations.AddField(
            model_name='prototype',
            name='height',
            field=models.IntegerField(default=0, verbose_name='высота'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='width',
            field=models.IntegerField(default=0, verbose_name='ширина'),
        ),
        migrations.AddField(
            model_name='screen',
            name='height',
            field=models.IntegerField(default=0, verbose_name='высота'),
        ),
        migrations.AddField(
            model_name='screen',
            name='width',
            field=models.IntegerField(default=0, verbose_name='ширина'),
        ),
    ]
