# Generated by Django 3.0.7 on 2020-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0004_auto_20200624_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='image_hover',
            field=models.FileField(default='', upload_to='images_prototypes/hover/', verbose_name='hover'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=16, verbose_name='название'),
        ),
    ]
