# Generated by Django 3.0.7 on 2020-11-21 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_auto_20201108_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='colors',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='UserElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('layout', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
