# Generated by Django 3.0.7 on 2020-06-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0005_auto_20200627_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='название')),
                ('slug', models.CharField(max_length=64, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'картегория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='CategoryPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Category',
                                               verbose_name='категория')),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Prototype')),
            ],
            options={
                'verbose_name': 'картегория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.RemoveField(
            model_name='element',
            name='group',
        ),
        migrations.DeleteModel(
            name='GroupElements',
        ),
        migrations.AddField(
            model_name='element',
            name='category_prototype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='content.CategoryPrototype'),
        ),
    ]
