# Generated by Django 3.0.7 on 2020-11-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20201121_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='background_color',
            field=models.TextField(default='#232323', verbose_name='макет'),
        ),
    ]
