# Generated by Django 3.0.7 on 2020-06-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0006_auto_20200630_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='layout_element',
            new_name='layout',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='layout_screen',
        ),
        migrations.AddField(
            model_name='element',
            name='active',
            field=models.BooleanField(default=True, verbose_name='on'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='base_layout',
            field=models.TextField(default='', verbose_name='начальный макет'),
        ),
        migrations.AddField(
            model_name='screen',
            name='layout',
            field=models.TextField(default='', verbose_name='макет'),
        ),
        migrations.AddField(
            model_name='screen',
            name='title',
            field=models.CharField(default='', max_length=32, verbose_name='название'),
        ),
    ]
