# Generated by Django 3.0.7 on 2020-06-30 15:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0007_auto_20200630_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='layout',
            field=tinymce.models.HTMLField(default='', verbose_name='макет'),
        ),
    ]
