# Generated by Django 3.0.7 on 2020-06-30 15:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0008_auto_20200630_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototype',
            name='base_layout',
            field=tinymce.models.HTMLField(default='', verbose_name='начальный макет'),
        ),
    ]
