# Generated by Django 3.0.7 on 2020-07-02 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0009_auto_20200630_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='last_change',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 9, 21, 33, 61485, tzinfo=utc),
                                       verbose_name='последние изменение'),
        ),
    ]
