# Generated by Django 3.0.7 on 2021-01-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userelement',
            name='user',
        ),
        migrations.AddField(
            model_name='userelement',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.Project'),
        ),
    ]
