# Generated by Django 3.0.7 on 2020-07-02 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0010_screen_last_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.FileField(upload_to='images_elements/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='last_change',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 9, 49, 28, 282155, tzinfo=utc),
                                       verbose_name='последние изменение'),
        ),
    ]
