# Generated by Django 3.0.7 on 2020-07-09 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0011_auto_20200702_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='last_change',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 16, 57, 43, 928598, tzinfo=utc),
                                       verbose_name='последние изменение'),
        ),
    ]
