# Generated by Django 3.0.7 on 2020-07-09 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0012_auto_20200709_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='last_change',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 16, 59, 25, 557953, tzinfo=utc),
                                       verbose_name='последние изменение'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='layout',
            field=models.TextField(default='', verbose_name='макет'),
        ),
    ]
