# Generated by Django 3.0.7 on 2020-07-16 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0013_auto_20200709_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='two_in_row',
            field=models.BooleanField(default=False, verbose_name='По 2 элемента'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='last_change',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 12, 26, 21, 405778, tzinfo=utc),
                                       verbose_name='последние изменение'),
        ),
    ]
