# Generated by Django 3.0.7 on 2020-07-17 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0014_auto_20200716_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, verbose_name='Значение')),
                ('slug', models.CharField(max_length=64, verbose_name='slug')),
            ],
        ),
        migrations.AlterField(
            model_name='screen',
            name='last_change',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 15, 41, 37, 802872, tzinfo=utc),
                                       verbose_name='последние изменение'),
        ),
    ]
