# Generated by Django 3.0.7 on 2021-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='position',
            field=models.IntegerField(default=0, verbose_name='позиция'),
        ),
    ]
