# Generated by Django 3.0.7 on 2021-03-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_screen_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='background_color',
            field=models.TextField(default='#FFFFFF'),
        ),
    ]
