# Generated by Django 3.0.7 on 2020-07-17 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0016_auto_20200717_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='last_change',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 15, 46, 34, 582632, tzinfo=utc),
                                       verbose_name='последние изменение'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Значение'),
        ),
    ]
