# Generated by Django 3.0.7 on 2020-07-17 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0017_auto_20200717_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='last_change',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 15, 48, 4, 179432, tzinfo=utc),
                                       verbose_name='последние изменение'),
        ),
    ]
