# Generated by Django 3.0.7 on 2021-03-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20210316_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWidthPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('image', models.FileField(upload_to='images_prototype_width/', verbose_name='изображение')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sharedproject',
            options={'verbose_name': 'Права на проект', 'verbose_name_plural': 'Права на проекты'},
        ),
        migrations.AddField(
            model_name='prototype',
            name='base_width',
            field=models.ManyToManyField(null=True, to='content.BaseWidthPrototype'),
        ),
    ]
