# Generated by Django 3.0.7 on 2021-03-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20210321_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basewidthprototype',
            name='image',
        ),
        migrations.AddField(
            model_name='basewidthprototype',
            name='dark_image',
            field=models.FileField(default=1, upload_to='images_prototype_width/', verbose_name='dark изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basewidthprototype',
            name='light_image',
            field=models.FileField(default=1, upload_to='images_prototype_width/', verbose_name='light изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prototype',
            name='base_width',
            field=models.ManyToManyField(null=True, to='content.BaseWidthPrototype', verbose_name='Список width'),
        ),
    ]
