# Generated by Django 3.0.7 on 2021-03-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20210321_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModesState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements', models.TextField()),
            ],
        ),
    ]
