# Generated by Django 3.0.7 on 2021-03-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20210326_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constant_colors',
            options={'verbose_name': 'цвет', 'verbose_name_plural': 'цвета'},
        ),
        migrations.AddField(
            model_name='constant_colors',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='constant_colors',
            name='to_prototype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constant_prototype', to='content.Prototype'),
        ),
        migrations.AlterField(
            model_name='constant_colors',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constant_colors', to='content.Project'),
        ),
        migrations.RemoveField(
            model_name='screen',
            name='constant',
        ),
        migrations.AddField(
            model_name='screen',
            name='constant',
            field=models.ManyToManyField(to='content.Constant_colors'),
        ),
    ]
