# Generated by Django 3.0.7 on 2021-05-06 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0028_clientstrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
