# Generated by Django 3.0.7 on 2021-05-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20210506_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=255)),
                ('live_mode', models.BooleanField()),
                ('cost', models.IntegerField()),
                ('interval', models.CharField(max_length=255)),
                ('name', models.TextField()),
            ],
        ),
    ]
