# Generated by Django 3.0.7 on 2021-05-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=500)),
                ('end_period', models.CharField(max_length=100)),
                ('start_period', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=255)),
                ('latest_invoice', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('subscription_end', models.CharField(max_length=255)),
                ('livemode', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='clientstrip',
            name='livemode',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientstrip',
            name='payment_status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientstrip',
            name='seanse',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
