# Generated by Django 3.0.7 on 2021-05-12 17:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_auto_20210512_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='styles',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
