# Generated by Django 3.0.7 on 2021-05-12 18:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_remove_screen_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='styles',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
