# Generated by Django 3.0.7 on 2021-05-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20210512_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='constant_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constant_screen', to='content.Constant_colors'),
        ),
    ]
