# Generated by Django 3.0.7 on 2021-05-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20210512_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='styles',
        ),
    ]
