# Generated by Django 3.0.7 on 2021-05-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientstrip',
            name='payment_status',
        ),
    ]
