# Generated by Django 3.0.7 on 2021-05-31 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0045_userelement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedproject',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
