# Generated by Django 3.0.7 on 2021-06-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_auto_20210531_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='base',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
