# Generated by Django 3.0.7 on 2021-06-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_screen_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstrip',
            name='use_trial',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
