# Generated by Django 3.0.7 on 2021-06-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_clientstrip_use_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='previewScreenId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview_screen', to='content.Screen'),
        ),
    ]
