# Generated by Django 3.0.7 on 2021-06-09 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0049_project_previewscreenid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('framework', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('news', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('theme', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
