# Generated by Django 3.0.7 on 2021-06-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_userabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='previewScreenId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_preview', to='content.Screen'),
        ),
    ]
