# Generated by Django 3.0.7 on 2021-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_auto_20210609_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='downloadCount',
            field=models.IntegerField(default=0),
        ),
    ]
