# Generated by Django 3.0.7 on 2021-06-09 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0052_userpermission_downloadcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
