# Generated by Django 3.0.7 on 2021-06-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0054_auto_20210609_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userabout',
            options={'verbose_name': 'Опросник', 'verbose_name_plural': 'Опросники'},
        ),
    ]
