# Generated by Django 3.0.7 on 2021-06-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_auto_20210612_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryprototype',
            options={'verbose_name': 'картегория_прототип', 'verbose_name_plural': 'категории_прототипы'},
        ),
    ]
