# Generated by Django 3.0.7 on 2021-06-26 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_auto_20210626_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='category_prototype',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.CategoryPrototype'),
        ),
    ]
