# Generated by Django 3.0.7 on 2021-06-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0058_auto_20210626_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryPrototype',
        ),
    ]
