# Generated by Django 3.0.7 on 2021-07-01 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_delete_categoryprototype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='constant_colors',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'element', 'verbose_name_plural': 'elements'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='prototype',
            options={'verbose_name': 'prototype', 'verbose_name_plural': 'prototypes'},
        ),
        migrations.AlterModelOptions(
            name='screen',
            options={'verbose_name': 'screen', 'verbose_name_plural': 'screens'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'setting', 'verbose_name_plural': 'settings'},
        ),
        migrations.AlterModelOptions(
            name='sharedproject',
            options={'verbose_name': 'shared project', 'verbose_name_plural': 'shared projects'},
        ),
        migrations.AlterModelOptions(
            name='socialuser',
            options={'verbose_name': 'social user', 'verbose_name_plural': 'social users'},
        ),
        migrations.AlterModelOptions(
            name='userabout',
            options={'verbose_name': 'questionnaire', 'verbose_name_plural': 'questionnaires'},
        ),
        migrations.AlterField(
            model_name='basewidthprototype',
            name='dark_image',
            field=models.FileField(upload_to='images_prototype_width/', verbose_name='dark image'),
        ),
        migrations.AlterField(
            model_name='basewidthprototype',
            name='light_image',
            field=models.FileField(upload_to='images_prototype_width/', verbose_name='light image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='prototype',
            field=models.ManyToManyField(null=True, to='content.Prototype', verbose_name='prototypes'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='two_in_row',
            field=models.BooleanField(default=False, verbose_name='2 elements'),
        ),
        migrations.AlterField(
            model_name='element',
            name='dark_layout',
            field=models.TextField(verbose_name='dark_layout'),
        ),
        migrations.AlterField(
            model_name='element',
            name='light_layout',
            field=models.TextField(verbose_name='light_layout'),
        ),
        migrations.AlterField(
            model_name='element',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='count',
            field=models.IntegerField(default=0, verbose_name='version period'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='base_width',
            field=models.ManyToManyField(null=True, to='content.BaseWidthPrototype', verbose_name='base width'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='device_name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='height',
            field=models.IntegerField(default=0, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='image',
            field=models.FileField(upload_to='images_prototypes/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='width',
            field=models.IntegerField(default=0, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='height',
            field=models.IntegerField(default=0, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last change'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='layout',
            field=models.TextField(default='', verbose_name='layout'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='position',
            field=models.IntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='title',
            field=models.CharField(default='', max_length=32, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='width',
            field=models.IntegerField(default=0, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.PositiveIntegerField(verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='provider',
            field=models.CharField(max_length=50, verbose_name='provider'),
        ),
    ]
