# Generated by Django 3.0.7 on 2021-07-09 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0061_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials_file', models.FileField(upload_to='firebase_credentials/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
