# Generated by Django 3.0.7 on 2021-07-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0063_auto_20210716_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='backendType',
            field=models.TextField(blank=True, null=True),
        ),
    ]
