# Generated by Django 3.0.7 on 2021-07-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0064_request_backendtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasesettings',
            name='credentials_file',
        ),
    ]
