# Generated by Django 3.0.7 on 2021-08-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_remove_firebasesettings_credentials_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='start',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='team',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.CharField(choices=[('START', 'start'), ('PROFESSIONAL', 'professional'), ('TEAM', 'team'), ('ENTERPRISE', 'enterprise')], default='START', max_length=25),
        ),
    ]
