# Generated by Django 3.0.7 on 2021-08-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0069_auto_20210802_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
