# Generated by Django 3.0.7 on 2021-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0070_category_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='isVideoExamplesDisabled',
            field=models.BooleanField(default=False),
        ),
    ]
