# Generated by Django 3.0.7 on 2021-08-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0071_userpermission_isvideoexamplesdisabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='link',
        ),
    ]
