# Generated by Django 3.0.7 on 2021-08-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0076_auto_20210805_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
