# Generated by Django 3.0.7 on 2021-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0077_promocode_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='free_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocode',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
