# Generated by Django 3.0.7 on 2021-08-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0078_auto_20210808_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('write', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
