# Generated by Django 3.0.7 on 2021-08-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0079_pluginauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('position', models.SmallIntegerField(default=0)),
                ('screen', models.ManyToManyField(null=True, to='content.Screen')),
            ],
        ),
    ]
