# Generated by Django 3.0.7 on 2021-08-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0081_category_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen_ScreenCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Screen_category/')),
                ('position', models.SmallIntegerField()),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Screen')),
                ('screencategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.ScreenCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='screencategory',
            name='screen',
        ),
        migrations.AddField(
            model_name='screencategory',
            name='screen',
            field=models.ManyToManyField(through='content.Screen_ScreenCategory', to='content.Screen'),
        ),
    ]
