# Generated by Django 3.0.7 on 2021-08-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0083_auto_20210821_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='copyCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='screen_screencategory',
            name='image',
            field=models.FileField(null=True, upload_to='screen_category/'),
        ),
    ]
