# Generated by Django 3.0.7 on 2021-08-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0086_auto_20210825_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basewidthprototype',
            options={'verbose_name': 'base width of prototypes', 'verbose_name_plural': 'base width of the prototype'},
        ),
        migrations.AlterModelOptions(
            name='clientstrip',
            options={'verbose_name': 'client stripe', 'verbose_name_plural': 'stripe clients'},
        ),
        migrations.AlterModelOptions(
            name='enterpriseuser',
            options={'verbose_name': 'enterprise user', 'verbose_name_plural': 'enterprise users'},
        ),
        migrations.AlterModelOptions(
            name='figmauser',
            options={'verbose_name': 'figma user', 'verbose_name_plural': 'figma users'},
        ),
        migrations.AlterModelOptions(
            name='firebaserequest',
            options={'verbose_name': 'firebase request', 'verbose_name_plural': 'firebase requests'},
        ),
        migrations.AlterModelOptions(
            name='firebasesettings',
            options={'verbose_name': 'firebase settings', 'verbose_name_plural': 'firebase settings'},
        ),
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'verbose_name': 'password reset', 'verbose_name_plural': 'password resets'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'price', 'verbose_name_plural': 'prices'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'promo code', 'verbose_name_plural': 'promo codes'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'request', 'verbose_name_plural': 'requests'},
        ),
        migrations.AlterModelOptions(
            name='screencategory',
            options={'verbose_name': 'screen category', 'verbose_name_plural': 'screen categories'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterModelOptions(
            name='tutorials',
            options={'verbose_name': 'tutorial', 'verbose_name_plural': 'tutorials'},
        ),
        migrations.AlterModelOptions(
            name='userelement',
            options={'verbose_name': 'user element', 'verbose_name_plural': 'user elements'},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'verbose_name': 'user permission', 'verbose_name_plural': 'user permissions'},
        ),
    ]
